tap "hashicorp/tap"
# replace basic commands with GNU/Linux version
brew "coreutils"
brew "diffutils"
brew "ed"
brew "findutils"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "gzip"
brew "iproute2mac"

# utility commands
brew "git"
brew "neovim"
brew "tree"
brew "asdf"
brew "tmux"
brew "jq"
brew "wget"
brew "unzip"
brew "fzf"
brew "ghq"
brew "gh"
brew "direnv"
brew "docker", link: false
brew "kubectl"
brew "kind"
brew "hashicorp/tap/terraform"
brew "awscli"

cask "visual-studio-code"
cask "karabiner-elements"
cask "google-japanese-ime"
cask "appcleaner"
cask "1password-cli"
cask "raycast"
cask "warp"