# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ['source']

[plugins.fzf-tab-completion]
github = 'lincheney/fzf-tab-completion'
use = ['fzf-zsh-completion.sh']
apply = ["defer"]

[plugins.fzf-tab-completion.hooks]
post = 'bindkey "^I" fzf_completion'

[plugins.fzf-git]
github = 'junegunn/fzf-git.sh'
apply = ["defer"]
